### ISSUE TITLE
Supporting Julia 0.5

### ISSUE THREAD

**Issue by mirestrepo** [fhs/ZipFile.jl#29]
Are there any plans to upgrade ZipFile to use Julia 0.5?

Under Julia 0.5 there are several deprecation warning and tests fail

**Comment by samoconnor** [comment]
@tkelman @fhs @yuyichao 

Does this https://github.com/dcjones/Zlib.jl/pull/27#issuecomment-245890410 mean that the v0.5 PRs for Zlib will not be merged? and that ZipFile.jl will not support v0.5?

I currently used ZipFile.jl as a fallback when InfoZip `unzip` is not available (in https://github.com/samoconnor/InfoZIP.jl)

Should I use https://github.com/yuyichao/LibArchive.jl instead?

**Comment by tkelman** [comment]
The lack of anyone having commit access to that package means I wouldn't rely on anything getting merged. We could redirect METADATA to point to a fork, but given the package has better-maintained replacements available, I'd advise switching away from Zlib.jl instead.

**Comment by yuyichao** [comment]
Unless someone find @dcjones or another Zlib collaborator then I don't think https://github.com/dcjones/Zlib.jl/pull/27 can be merged. Given new code is supposed to use `Libz` instead we may not fork it either.

The commit that closes this issue seems to have merged a wrong version of https://github.com/fhs/ZipFile.jl/pull/26 so the PR is still needed and can be merged independent of the dependency.

LibArchive is supposed to support multiple format of archives although it also supports raw ones. You are welcome to use it if you find it useful (and report issues if you hit one) but it is not meant to replace any other packages.

**Comment by samoconnor** [comment]
It seems like @fhs has a descition to make:
 - Port ZipFile.jl to use Libz.jl, or
 - Fork and maintain fhs/Zlib.jl, or
 - Merge the Zilb.jl source code into ZipFile.jl

Is that a fair summary of the options?

**Comment by fhs** [comment]
> Merge the Zilb.jl source code into ZipFile.jl

I'm going with this option for now because Libz.jl doesn't support raw deflate compression/decompression, which is what we need. I could send a PR to Libz.jl to add support for that but I'd rather not depend on yet another library that might be abandoned in the future. The copied code is only about 375 lines of code.
